import React from 'react';

// Components
import ContentSection from "../../components/ContentSection";
import ProjectLogistics from "../../components/ProjectLogistics";

// other
import { AwesomeButton } from "react-awesome-button";
import Fade from 'react-reveal/Fade';

function BeatfoxflowReflection(props) {

    let titleStyle = {
        fontSize: "40px",
        color: "#ED6167"
    }

    let subtitleStyle = {
        fontSize: "30px",
        color: "#ED6167"
    }

    let pStyle = {
        fontSize: "20px"
    }

    let linkStyle = {
        color: "#ED6167"
    }

    let liStyle = {
        paddingTop: "10px"
    }
    
    let divStyle = {
        width: "60%",
        margin: "auto"
    }

    let imgStyle = {
        height: "200px",
        width: "auto",
        margin: "auto",
        display: "block"
    }

    let flexboxStyle = {
        display: "flex",
        width: "90%",
        margin: "auto",
        flexWrap: "wrap",
        justifyContent: "space-evenly"
    }

    return(
        <div>
            {/* Reflection */}
            <ContentSection 
                heading="Beat Fox Flow"
                content="Beatfox Flow is a 2D rhythm based platformer game with procedural music, generated by the enemies, objects, and action on screen."
                src="images/beatfoxflowlogo.png"
            />

            <ProjectLogistics
                team1name="Developers"
                team1="Joshua Maza"    
                scope="Game Development, Character and Level Design, Sprite Illustration and Animation"
                time="Sept 1- Sept 15 2018 (14 Days)"
                tools="Unity, Piskel"
            />

            <Fade>
                <div style={divStyle}>
                    <h1 style={titleStyle}>Project Glossary</h1>
                    <ol style={pStyle}>
                        <li style={liStyle}><b>Overview</b> - Music and accessibility in gaming</li>
                        <li style={liStyle}><b>Beat Based System</b> - Movement in a rhythm platformer</li>
                        <li style={liStyle}><b>Procedural Music</b> - Creating music without writing a single note</li>
                        <li style={liStyle}><b>Character Design</b> - Foxes, plants, trees, and more</li>
                        <li style={liStyle}><b>Takeaways</b> - Lessons I learned from this project</li>
                    </ol>
                </div>
            </Fade>

            <Fade>
                <div style={divStyle}>
                    <h1 style={titleStyle}>Overview</h1>
                    <h1 style={subtitleStyle}>Music and accessibility in gaming</h1>
                    <p style={pStyle}>You always hear about how games are innovating in areas related to graphics, gameplay mechanics, or
                    the genres they reside in, however you rarely, if at all, hear anything related to accessbility. Arguably the
                    market section of gamers with disabilities may not be large, but that could also be in turn because of how the gaming
                    industry doesn't often consider accessibility. I believe that introducing accessibility considerations to game
                    design presents a unique challenge that can yield more innovative games. In particular, one way I approach this
                    mindset is by leveraging my understanding of audio and music theory to introduce more accessibly gameplay mechanics.</p>

                    <p style={pStyle}>The motivation for this project came from <a href="https://itch.io/jam/musicgamejam2018" style={linkStyle} target="_blank">Music Game Jam 2018</a>, a game
                    jam themed around making any music or audio themed game. This highly interpretable theme appeals to nearly all my strengths,
                    and I wanted to take it one step further by also incorporating aspects of <b>accessibility</b> in gaming. I believe that this creative
                    restraint, when combined with audio, presents a unique intersection for audio and game development that has the potential to yield highly
                    creative applications in accessible gaming.</p>
                </div>
            </Fade>

            <Fade>
                <div style={divStyle}>
                    <iframe
                        src={{margin: "auto"}} 
                        frameborder="0" 
                        src="https://itch.io/embed/305407?border_width=5&amp;bg_color=222222&amp;fg_color=eeeeee&amp;border_color=363636" 
                        width="216" 
                        height="175">
                            <a href="https://mazaa.itch.io/beatfox-flow">BeatFox Flow by MAZAA</a>
                    </iframe>        
                </div>
            </Fade>

            <ContentSection 
                heading="Beat Based System"
                subheading="Movement in a rhythm platformer"
                content="Inspired by the theme, I wanted to create a game literally driven by the music itself.
                At the core of music is the musical beat, which is a consistent pulse that keeps music in time.
                Carrying this understanding over from music, I have a 'composer' who emits pulses at regular
                intervals to control the events of the entire game. One of these many events relates to player 
                movement."
                src="images/beatfoxflowgameplay/1.PNG"
            />

            <ContentSection 
                heading=""
                subheading="Jumping to the beat"
                content="One unique mechanic I added to the game was restricting the player's movement
                by only allowing them to jump 'on beat', or within a certain time window of the game's consistent pulses.
                This was more of a whimsical mechanic I added to adhere more to the theme of a music based game, but
                in combination with timing based enemies and obstacles, it presents additional gameplay difficulty."
                src="images/beatfoxflowgameplay/5.gif"
                right={true}
            />

            <ContentSection 
                heading="Procedural Music"
                subheading="Creating music without writing a single note"
                content="The backbone of the game is the beat based event system I created. Using it, I also made it
                trigger the actions of enemies, who in turn would play a sound along with that action. Different sounds like
                a kick drum, snare, hi hat, or tonal elements like beeps and bells all help to characterize both the
                obstacle the enemy presents, its distance, as well as works to compose music. It works in a similar manner to
                a sequencer, except instead of playing samples I'm placing enemies in the map."
                src="images/beatfoxflowgameplay/3.PNG"
            />

            <ContentSection 
                heading=""
                subheading="Animations and timing"
                content="In addition to triggering enemies, I drew frames by hand and aligned them to match with the sound
                they emitted such that the apex of the animation triggers the sound. I also aligned hitboxes so that hitboxes
                only appear in the right spots when the beat is triggered. All of this adds up to a precise enemy that is
                in time with the music and gameplay."
                src="images/beatfoxflowgameplay/11.gif"
                right={true}
            />

            <ContentSection 
                heading="Character Design"
                subheading="They're kind of adorable"
                content="All of the characters, enemies, and objects in the game were hand drawn and animated sprites.
                They're rather endearing and helped me to better understand shading, frame animation, and motion with pixel art."
                src="images/beatfoxflowgameplay/7.gif"
            />

            <Fade>
                <div style={flexboxStyle}>
                    <img src="images/beatfoxflowgameplay/8.gif" style={imgStyle}/>
                    <img src="images/beatfoxflowgameplay/9.gif" style={imgStyle}/>
                    <img src="images/beatfoxflowgameplay/6.gif" style={imgStyle}/>
                    <img src="images/beatfoxflowgameplay/12.gif" style={imgStyle}/>
                    <img src="images/beatfoxflowgameplay/10.gif" style={imgStyle}/>
                </div>
            </Fade>

            <Fade>
                <div style={divStyle}>
                    <h1 style={titleStyle}>Takeaways</h1>
                    <p style={pStyle}><b>A game's mechanics have to be solid</b></p>
                    <p style={pStyle}>This sounds so obvious but even triple A developers forget it sometimes. The final product for this game
                    was not what I imagined at the outset because the movement system was terrible. In theory and in my mind it made perfect
                    sense, but execution wise it was hard to perfect. Several YouTubers played my game, and they all had the similar feeling
                    of frustration trying to get the player to jump. It resulted in quitting the game early, and I realized that poor mechanics 
                    is an important pain point to address when designing the gameplay. Also, I need to keep in mind that my increasing aptitiude 
                    for these mechanics while playtesting hinders my ability to accurately judge difficulty because I'll naturally get good 
                    at my own game.</p>
                    <br />
                    <p style={pStyle}><b>Understand the limitations of your engine and system implementations</b></p>
                    <p style={pStyle}>I used Unity to develop this game, which is a pretty robust game engine for both 2D and 3D. However what
                    I failed to anticipate was that my implementatino of my beat system overly stressed the game by overusing Unity's update system.
                    Given the short time frame, I couldn't revise the system, but understanding the impact and resource consumption of the systems you 
                    create compared to the limitations of your engine is key for doing anything remotely innovative.</p>
                    <br />
                    <p style={pStyle}><b>Don't get too attached to your initial idea</b></p>
                    <p style={pStyle}>At the time, I really loved the word 'procedural' and was inspired by <i>Red Dead Redemption</i>, an old game 
                    developed by <i>Rockstar Games</i> that made use of a procedural music system that reacted to the player's surroundings. 
                    This idea ended up being the foundation for many of the other ideas I had for this game. In retrospect, I wish I had ideated 
                    a little more to have more options instead of initally getting excited and running away with a single idea only to find it 
                    might not have been the best one.</p>
                </div>
            </Fade>


        </div>
    )
}

export default BeatfoxflowReflection;